import java.util.Scanner;

/**
 * @author: Mohammad Almotaani
 * @since: 2023-02-23
 * 
 */

public class Helper {

	/**
	 * To avoid writing a lot of Scanner statements, I created a static Scanner
	 * object called 'S' to be used within the 'input()' and 'inputInt()' methods.
	 */
	private static final Scanner S = new Scanner(System.in);

	/* Don't let anyone instantiate this class */
	private Helper() {
	}

	/**
	 * input is a method that can be used as Scanner for String values. The argument
	 * 'message' will be printed as instruction for user. Think of it Like Python
	 * built-in function 'input()'.
	 */
	public static String input(String message) {
		System.out.print(message); 
		return S.nextLine(); 
	}

	/**
	 * inputInt is a method that can be used as Scanner for Integer values. The
	 * argument 'message' will be printed as instruction for the user. Think of it
	 * like the built-in function 'input()' from Python programming language. Note
	 * that it contains a 'try... catch' statement to deal with unexpected inputs
	 * other than integers. The method will return if and only if the input is an
	 * integer string(String can be converted to int).
	 */
	public static int inputInt(String message) {
		int result;

		// The purpose of while loop is to force the user to enter the right
		// output(String can be converted to primitive type int).
		while (true) {
			try {
				result = Integer.parseInt(input(message)); // Use input() method to get String then convert it to
															// integer.
				break;
			} catch (NumberFormatException e) {
				System.err.println("\nInvalid input!");
				System.out.println("The number should not be a large number or contain chracters.\n");
			}

		}

		return result;
	}

	/**
	 * bin() is a method to convert decimal numbers to binary string
	 * It use 'Integer.toBinaryString()' method from class Integer.
	 */
	public static String bin(int decimal) {
		return Integer.toBinaryString(decimal);
	}

	/**
	 * hex() is a method to convert decimal numbers to hexadecimal string
	 *  It use 'Integer.toHexString()' method from class Integer.
	 */
	public static String hex(int decimal) {
		return Integer.toHexString(decimal);
	}

	/**
	 * checkAnswer() is a method to check if the user answer is correct.
	 */
	public static boolean checkAnswer(String userAnswer, String correctAnswer) {
		return userAnswer.equalsIgnoreCase(correctAnswer);
	}

	/**
	 * generateRandomInteger() is a method to generate random number. The random
	 * number is greater than or equal minimum and less than maximum. Example:
	 * create variable and initialize it's value to random number between 10 and 20.
	 * Answer : int n = generateRandomInteger(10, 21). The example above will
	 * generate a number between 10 and 20. Note that the maximum number(in this case 21) is not included
	 * and the maximum value will generated by method is 20.
	 */
	public static int generateRandomInteger(int minimum, int maximum) { 
		return (int) ((Math.random() * (maximum - minimum)) + minimum);
	}

	public static void main(String[] testHelper) {
		String x = input("Enter a String: ");
		String s = input("Enter a String: ");
		System.out.println("x = " + x + " s = " + s);
		System.out.println("is same: " + checkAnswer(s, x));
		int min = inputInt("Enter minimum value: ");
		int max = inputInt("Enter maximum value: ");
		System.out.printf("Random number between %d and %d: %d \n", min, max, generateRandomInteger(min, max));
		System.out.println("END");
	}

}
